"""
Generate a SAMPLE campaign CSV + report WITHOUT hardware, so the analysis and
reporting pipeline can be exercised and demoed immediately.

This is a pipeline smoke-test / demo only. The numbers are synthetic and the
generated report is clearly labelled as such. Real runs use run_campaign.py.

  python scripts/demo_pipeline.py
"""

import random
import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from pmu_val.dut import DUT
from pmu_val.sequencer import Campaign
from pmu_val import report as R

random.seed(7)


def main():
    dut = DUT.from_yaml(ROOT / "config" / "dut_qc3.yaml")
    csv_path = ROOT / "data" / "campaign_demo.csv"
    if csv_path.exists():
        csv_path.unlink()
    campaign = Campaign(dut, csv_path)

    units = ["U1", "U2", "U3", "U4", "U5"]
    temps = [5, 25, 50]
    vins = [6, 7, 8, 9, 10, 11, 12]

    for unit in units:
        # each unit gets a small fixed offset = part-to-part (process) spread
        unit_off = random.gauss(0, 0.01)
        for rail_name, rail in dut.rails.items():
            nom = rail.vout_nom
            for temp in temps:
                # temp coefficient: small drift with temperature
                tdrift = (temp - 25) * 0.0004 * nom
                # line regulation across Vin
                vouts = [nom * (1 + unit_off) + tdrift + random.gauss(0, 0.003 * nom)
                         + (0.0006 * nom if v < nom + 1 else 0) for v in vins]
                line_reg = 100 * (max(vouts) - min(vouts)) / nom
                campaign.check_and_record("line_reg_pct", line_reg, rail_name,
                                          unit_id=unit, temp_c=temp)
                # load regulation
                load_reg = abs(random.gauss(2.0, 0.6)) + (0.5 if temp == 50 else 0)
                campaign.check_and_record("load_reg_pct", load_reg, rail_name,
                                          unit_id=unit, vin=nom + 2, temp_c=temp)
                # efficiency
                base_eff = {5.0: 88, 9.0: 91, 12.0: 92}.get(nom, 90)
                eff = base_eff + random.gauss(0, 1.2) - (1.5 if temp == 50 else 0)
                campaign.check_and_record("efficiency_pct", eff, rail_name,
                                          unit_id=unit, vin=nom + 2,
                                          iout=0.5, temp_c=temp)

    note = ("DEMO / SYNTHETIC DATA -- generated by demo_pipeline.py to exercise "
            "the analysis and reporting pipeline. NOT real measurements. "
            "Real runs use run_campaign.py against physical hardware.")
    html_path = R.write_report(campaign.rows, dut,
                               ROOT / "reports" / "demo_report.html", note)
    print(f"Rows: {len(campaign.rows)}")
    print(f"Demo report: {html_path}")


if __name__ == "__main__":
    main()
